sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install pydoc
    - pip install pylint

before_script:
    - uname -a
    - printenv | sort
    - ls -al /home/travis/virtualenv/python3.5.2/bin/
    - make versions

script:
    - date
    - ls -al
    - make test
